GET http://localhost:3456/

# NOT found is expected

###
GET http://localhost:3456/api/v1/

# shows a custom not found message

###
GET http://localhost:3456/api/v1/users HTTP/1.1

###
GET http://localhost:3456/api/v1/books 
Accept: application/json

###
GET http://localhost:3456/api/v1/books 
Accept: text/plain
Origin: http://localhost:10000

###
GET http://localhost:3456/api/v1/books 
Accept: application/octet-stream

###
POST http://localhost:3456/api/v1/books/new
Content-Type: 


